#pragma once
#include <iostream>
#include <fstream>
#include <windows.h>
#include "SFML/Audio.hpp"
#include "SFML/Window.hpp"
#include "Text.h"
#include "Movement.h"
#include "../Levels/Levels.h"
#include "../Menu/Menu.h"
#include "../Menu/Inventory.h"
#include "../Memories/Memories.h"
#include "../Enemy/Enemy.h"
#include "../Music/Sound.h"